 # A scrape configuration containing exactly one endpoint to scrape from node_exporter running on a host:
global:
  scrape_interval: 10s

scrape_configs:
   # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
   - job_name: 'node'

   # metrics_path defaults to '/metrics'
   # scheme defaults to 'http'.

     static_configs:
     - targets: ['localhost:8001']
